import 'componentes/cartao_tabela.dart';
import 'data/nav_bar_data.dart';
import 'componentes/tabela_wigets.dart';
import 'constantes.dart' as Const;
import 'package:flutter/material.dart';
import 'componentes/VSD.dart';

// CCD Dados

NavBarData ccddata = NavBarData(
  conteudo: [
    VSD(
      id: 0,
      imagem: Const.kImgs[0],
      conteudoLista: null,
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Bolo',
    ),
    VSD(
      id: 1,
      imagem: Const.kImgs[1],
      conteudoLista: null,
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Casa',
    ),
    VSD(
      id: 2,
      imagem: Const.kImgs[2],
      conteudoLista: null,
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Comida',
    ),
    VSD(
      id: 3,
      imagem: Const.kImgs[3],
      conteudoLista: null,
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Futebol',
    ),
    VSD(
      id: 4,
      imagem: Const.kImgs[4],
      conteudoLista: null,
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Gatos',
    ),
    VSD(
      id: 5,
      imagem: Const.kImgs[5],
      conteudoLista: null,
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Video Game',
    ),
    VSD(
      id: 6,
      imagem: Const.kImgs[6],
      conteudoLista: null,
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Crianças',
    ),
    VSD(
      id: 7,
      imagem: Const.kImgs[7],
      conteudoLista: null,
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Hamburgers',
    ),
    VSD(
      id: 8,
      imagem: Const.kImgs[8],
      conteudoLista: null,
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Mudança',
    ),
    VSD(
      id: 9,
      imagem: Const.kImgs[9],
      conteudoLista: null,
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Bebê',
    ),
  ],
);

// CCDG Dados

NavBarData ccdgdata = NavBarData(
  conteudo: [
    TabelaWidget(
      id: 0,
      imagem: './assets/cards/pessoas/familia.jpeg',
      descricao: 'Pessoas',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/pai.jpeg'),
          texto: 'Pai',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/mae.jpeg'),
          texto: 'Mãe',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/avo_mae.jpeg'),
          texto: 'Avó',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/avo_pai.jpeg'),
          texto: 'Avô',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/amigo.jpeg'),
          texto: 'Amigo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/irmaos.jpeg'),
          texto: 'Irmão',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/sister.jpeg'),
          texto: 'Irmã',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/tio.jpeg'),
          texto: 'Tio',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/tia.jpeg'),
          texto: 'Tia',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/familia.jpeg'),
          texto: 'Família',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),

        // linha 2

        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/gato.jpeg'),
          texto: 'Gato',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/cachorro.jpeg'),
          texto: 'Cachorro',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/homem.jpeg'),
          texto: 'Homem',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/mulher.jpeg'),
          texto: 'Mulher',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/menino.jpeg'),
          texto: 'Menino',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/menina.jpeg'),
          texto: 'Menina',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/bebe.jpeg'),
          texto: 'Bebê',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/medico.jpeg'),
          texto: 'Médico',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/pessoa.jpeg'),
          texto: 'Pessoa',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/professora.jpeg'),
          texto: 'Professora',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 9,
        ),
        // linha 3
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/professora2.jpeg'),
          texto: 'Colegas',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 0,
        ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/mae.jpeg'),
        //   texto: 'Mãe',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 1,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/avo_mae.jpeg'),
        //   texto: 'Avó',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 2,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/avo_pai.jpeg'),
        //   texto: 'Avô',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 3,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/amigo.jpeg'),
        //   texto: 'Amigo',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 4,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/irmaos.jpeg'),
        //   texto: 'Irmão',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 5,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/sister.jpeg'),
        //   texto: 'Irmã',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 6,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/tio.jpeg'),
        //   texto: 'Tio',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 7,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/tia.jpeg'),
        //   texto: 'Tia',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 8,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/familia.jpeg'),
        //   texto: 'Família',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 9,
        // ),
      ],
    ),
    TabelaWidget(
      id: 1,
      imagem: './assets/cards/pronomes/default.png',
      descricao: 'Pronomes',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Eu',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Meu',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Você',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Seu',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Ele',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Ela',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Dele',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Dela',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Aquilo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Aquele',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),

        // linha 2

        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Aquela',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Eles',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Nós',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Nosso',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Deles',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Delas',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Ninguém',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Nenhuma',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Nenhum',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Esses',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 9,
        ),
      ],
    ),
    TabelaWidget(
      id: 2,
      imagem: './assets/cards/pronomes/default.png',
      descricao: 'Verbos',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Fazer',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Sair',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Ir',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Telefonar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Ajudar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Correr',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Caminhar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Continuar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Parar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Brincar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),
      ],
    ),
    TabelaWidget(
      id: 3,
      imagem: './assets/cards/pronomes/default.png',
      descricao: 'Sentimentos',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Alegre',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Bravo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Faminto',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Avô',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Triste',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Feliz',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Mau',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Bom',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Frio',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Quente',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),

        // linha 2

        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Sozinho',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Errado',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Doce',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Salgado',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Limpo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Sujo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 5,
        ),
      ],
    ),
    TabelaWidget(
      id: 4,
      imagem: './assets/cards/pronomes/default.png',
      descricao: 'Coisas',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'TV',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Bola',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Computador',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Video Game',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Casa',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Presente',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Boneco',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Boneca',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Balão',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Carro',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),

        // linha 2

        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Moto',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'CD',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Árvore',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Vento',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Núvem',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Sol',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Céu',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Guarda-Chuva',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Bicicleta',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Avião',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 9,
        ),
        // linha 3
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Dinheiro',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Cama',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Copo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Elevador',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 3,
        ),
      ],
    ),
    TabelaWidget(
      id: 5,
      imagem: './assets/cards/pronomes/default.png',
      descricao: 'Comidas',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Comida',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Almoço',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Jantar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Café da Manhã',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Queijo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Bife',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Salada',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Margarina',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Manteiga',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Chocolate',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),

        // linha 2

        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Chocolate Quente',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Água',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Refrigerante',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Lanche',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 3,
        ),
      ],
    ),
  ],
);
