import 'package:tcc/componentes/caixa_texto.dart';

import 'componentes/cartao_tabela.dart';
import 'data/nav_bar_data.dart';
import 'constantes.dart' as Const;
import 'package:flutter/material.dart';
import 'modelo/ponto_referencia.dart';
import 'modelo/vsd_modelo.dart';
import 'modelo/tabela_modelo.dart';

NavBarData ccddata = NavBarData(
  conteudo: [
    VSDModelo(
      key: Key('0'),
      imagem: Const.kImgs[0],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(120.0, 133.0),
          Offset(217.0, 209.0),
          'Morango',
          Key('P0'),
        ),
        PontoReferencia.fromPoints(
          Offset(202.0, 280.0),
          Offset(268.0, 351.0),
          'Recheio',
          Key('P01'),
        ),
        PontoReferencia.fromPoints(
          Offset(356.0, 365.0),
          Offset(465.0, 446.0),
          'Chocolate Branco',
          Key('P02'),
        ),
      ],
      id: 0,
      mini: Image.asset(Const.kImgs[0]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Bolo',
    ),
    VSDModelo(
      key: Key('1'),
      imagem: Const.kImgs[1],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(299.0, 231.0),
          Offset(419.0, 482.0),
          'Árvore',
          Key('P1'),
        ),
        PontoReferencia.fromPoints(
          Offset(658.0, 99.0),
          Offset(697.0, 151.0),
          'Chaminé',
          Key('P11'),
        )
      ],
      id: 1,
      mini: Image.asset(Const.kImgs[1]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Casa',
    ),
    VSDModelo(
      key: Key('2'),
      imagem: Const.kImgs[2],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(692.0, 42.0),
          Offset(721.0, 85.0),
          'Brinco',
          Key('P2'),
        ),
        PontoReferencia.fromPoints(
          Offset(324.0, 42.0),
          Offset(470.0, 105.0),
          'Garfo',
          Key('P21'),
        ),
        PontoReferencia.fromPoints(
          Offset(160.0, 420.0),
          Offset(722.0, 544.0),
          'Prato',
          Key('P21'),
        )
      ],
      id: 2,
      mini: Image.asset(Const.kImgs[2]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Comida',
    ),
    VSDModelo(
      key: Key('3'),
      imagem: Const.kImgs[3],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(380.0, 360.0),
          Offset(429.0, 408.0),
          'Bola',
          Key('P3'),
        ),
        PontoReferencia.fromPoints(
          Offset(526.0, 69.0),
          Offset(619.0, 209.0),
          'Árbitro',
          Key('P31'),
        ),
        PontoReferencia.fromPoints(
          Offset(117.0, 113.0),
          Offset(264.0, 187.0),
          'Placa',
          Key('P32'),
        )
      ],
      id: 3,
      mini: Image.asset(Const.kImgs[3]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Futebol',
    ),
    VSDModelo(
      key: Key('4'),
      imagem: Const.kImgs[4],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(8.0, 232.0),
          Offset(580.0, 513.0),
          'Filhotes',
          Key('P4'),
        ),
        PontoReferencia.fromPoints(
          Offset(574.0, 31.0),
          Offset(770.0, 223.0),
          'Mãe gatinhos',
          Key('P41'),
        )
      ],
      id: 4,
      mini: Image.asset(Const.kImgs[4]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Gatos',
    ),
    VSDModelo(
      key: Key('5'),
      imagem: Const.kImgs[5],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(291.0, 37.0),
          Offset(587.0, 128.0),
          'Nintendo',
          Key('P5'),
        ),
        PontoReferencia.fromPoints(
          Offset(90.0, 239.0),
          Offset(635.0, 472.0),
          'Controle',
          Key('P51'),
        )
      ],
      id: 5,
      mini: Image.asset(Const.kImgs[5]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Vídeo game',
    ),
    VSDModelo(
      key: Key('6'),
      imagem: Const.kImgs[6],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(215.0, 44.0),
          Offset(644.0, 435.0),
          'Irmãos',
          Key('P6'),
        )
      ],
      id: 6,
      mini: Image.asset(Const.kImgs[6]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Crianças',
    ),
    VSDModelo(
      key: Key('7'),
      imagem: Const.kImgs[7],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(23.0, 464.0),
          Offset(158.0, 548.0),
          'Alface',
          Key('P7'),
        ),
        PontoReferencia.fromPoints(
          Offset(269.0, 122.0),
          Offset(402.0, 241.0),
          'Hamburger',
          Key('P71'),
        )
      ],
      id: 7,
      mini: Image.asset(Const.kImgs[7]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Hamburgers',
    ),
    VSDModelo(
      key: Key('8'),
      imagem: Const.kImgs[8],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(5.0, 435.0),
          Offset(80.0, 553.0),
          'Pneu',
          Key('P8'),
        ),
        PontoReferencia.fromPoints(
          Offset(781.0, 14.0),
          Offset(838.0, 554.0),
          'Cerca',
          Key('P81'),
        ),
        PontoReferencia.fromPoints(
          Offset(403.0, 7.0),
          Offset(491.0, 276.0),
          'Menina',
          Key('P82'),
        ),
        PontoReferencia.fromPoints(
          Offset(249.0, 290.0),
          Offset(589.0, 403.0),
          'Menino',
          Key('P83'),
        )
      ],
      id: 8,
      mini: Image.asset(Const.kImgs[8]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Mudança',
    ),
    VSDModelo(
      key: Key('9'),
      imagem: Const.kImgs[9],
      conteudoLista: null,
      pontosReferencia: [],
      id: 9,
      mini: Image.asset(Const.kImgs[9]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Bebê',
    ),
  ],
);

// CCD Dados
NavBarData ccddata2 = NavBarData(
  conteudo: [
    VSDModelo(
      key: Key('0'),
      imagem: Const.kImgs[0],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(120.0, 133.0),
          Offset(217.0, 209.0),
          'Morango',
          Key('P0'),
        ),
        PontoReferencia.fromPoints(
          Offset(202.0, 280.0),
          Offset(268.0, 351.0),
          'Recheio',
          Key('P01'),
        ),
        PontoReferencia.fromPoints(
          Offset(356.0, 365.0),
          Offset(465.0, 446.0),
          'Chocolate Branco',
          Key('P02'),
        ),
      ],
      id: 0,
      mini: Image.asset(Const.kImgs[0]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Bolo 2',
    ),
    VSDModelo(
      key: Key('1'),
      imagem: Const.kImgs[1],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(299.0, 231.0),
          Offset(419.0, 482.0),
          'Árvore',
          Key('P1'),
        ),
        PontoReferencia.fromPoints(
          Offset(658.0, 99.0),
          Offset(697.0, 151.0),
          'Chaminé',
          Key('P11'),
        )
      ],
      id: 1,
      mini: Image.asset(Const.kImgs[1]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Casa 2',
    ),
    VSDModelo(
      key: Key('2'),
      imagem: Const.kImgs[2],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(692.0, 42.0),
          Offset(721.0, 85.0),
          'Brinco',
          Key('P2'),
        ),
        PontoReferencia.fromPoints(
          Offset(324.0, 42.0),
          Offset(470.0, 105.0),
          'Garfo',
          Key('P21'),
        ),
        PontoReferencia.fromPoints(
          Offset(160.0, 420.0),
          Offset(722.0, 544.0),
          'Prato',
          Key('P21'),
        )
      ],
      id: 2,
      mini: Image.asset(Const.kImgs[2]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Comida 2',
    ),
    VSDModelo(
      key: Key('3'),
      imagem: Const.kImgs[3],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(380.0, 360.0),
          Offset(429.0, 408.0),
          'Bola',
          Key('P3'),
        ),
        PontoReferencia.fromPoints(
          Offset(526.0, 69.0),
          Offset(619.0, 209.0),
          'Árbitro',
          Key('P31'),
        ),
        PontoReferencia.fromPoints(
          Offset(117.0, 113.0),
          Offset(264.0, 187.0),
          'Placa',
          Key('P32'),
        )
      ],
      id: 3,
      mini: Image.asset(Const.kImgs[3]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Futebol 2',
    ),
    VSDModelo(
      key: Key('4'),
      imagem: Const.kImgs[4],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(8.0, 232.0),
          Offset(580.0, 513.0),
          'Filhotes 2',
          Key('P4'),
        ),
        PontoReferencia.fromPoints(
          Offset(574.0, 31.0),
          Offset(770.0, 223.0),
          'Mãe gatinhos',
          Key('P41'),
        )
      ],
      id: 4,
      mini: Image.asset(Const.kImgs[4]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Gatos 2',
    ),
    VSDModelo(
      key: Key('5'),
      imagem: Const.kImgs[5],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(291.0, 37.0),
          Offset(587.0, 128.0),
          'Nintendo 2',
          Key('P5'),
        ),
        PontoReferencia.fromPoints(
          Offset(90.0, 239.0),
          Offset(635.0, 472.0),
          'Controle 2',
          Key('P51'),
        )
      ],
      id: 5,
      mini: Image.asset(Const.kImgs[5]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Vídeo game 2',
    ),
    VSDModelo(
      key: Key('6'),
      imagem: Const.kImgs[6],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(215.0, 44.0),
          Offset(644.0, 435.0),
          'Irmãos 2',
          Key('P6'),
        )
      ],
      id: 6,
      mini: Image.asset(Const.kImgs[6]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Crianças 2',
    ),
    VSDModelo(
      key: Key('7'),
      imagem: Const.kImgs[7],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(23.0, 464.0),
          Offset(158.0, 548.0),
          'Alface 2',
          Key('P7'),
        ),
        PontoReferencia.fromPoints(
          Offset(269.0, 122.0),
          Offset(402.0, 241.0),
          'Hamburger 2',
          Key('P71'),
        )
      ],
      id: 7,
      mini: Image.asset(Const.kImgs[7]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Hamburgers 2',
    ),
    VSDModelo(
      key: Key('8'),
      imagem: Const.kImgs[8],
      conteudoLista: null,
      pontosReferencia: [
        PontoReferencia.fromPoints(
          Offset(5.0, 435.0),
          Offset(80.0, 553.0),
          'Pneu',
          Key('P8'),
        ),
        PontoReferencia.fromPoints(
          Offset(781.0, 14.0),
          Offset(838.0, 554.0),
          'Cerca',
          Key('P81'),
        ),
        PontoReferencia.fromPoints(
          Offset(403.0, 7.0),
          Offset(491.0, 276.0),
          'Menina',
          Key('P82'),
        ),
        PontoReferencia.fromPoints(
          Offset(249.0, 290.0),
          Offset(589.0, 403.0),
          'Menino',
          Key('P83'),
        )
      ],
      id: 8,
      mini: Image.asset(Const.kImgs[8]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Mudança 2',
    ),
    VSDModelo(
      key: Key('9'),
      imagem: Const.kImgs[9],
      conteudoLista: null,
      pontosReferencia: [],
      id: 9,
      mini: Image.asset(Const.kImgs[9]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Bebê 2',
    ),
  ],
);

// CCDG Dados

NavBarData ccdgdata = NavBarData(
  conteudo: [
    // Pessoas
    TabelaModelo(
      key: Key('0'),
      imagem: './assets/cards/pessoas/familia.jpeg',
      id: 0,
      mini: Image.asset('./assets/cards/pessoas/familia.jpeg'),
      descricao: 'Pessoas',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/pai.jpeg'),
          texto: 'Pai',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
          onTap: (oi) {
            print(oi);
          },
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/mae.jpeg'),
          texto: 'Mãe',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/avo_mae.jpeg'),
          texto: 'Avó',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/avo_pai.jpeg'),
          texto: 'Avô',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/amigo.jpeg'),
          texto: 'Amigo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/irmaos.jpeg'),
          texto: 'Irmão',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/sister.jpeg'),
          texto: 'Irmã',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/tio.jpeg'),
          texto: 'Tio',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/tia.jpeg'),
          texto: 'Tia',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/familia.jpeg'),
          texto: 'Família',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),

        // linha 2

        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/gato.jpeg'),
          texto: 'Gato',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/cachorro.jpeg'),
          texto: 'Cachorro',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/homem.jpeg'),
          texto: 'Homem',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/mulher.jpeg'),
          texto: 'Mulher',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/menino.jpeg'),
          texto: 'Menino',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/menina.jpeg'),
          texto: 'Menina',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/bebe.jpeg'),
          texto: 'Bebê',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/medico.jpeg'),
          texto: 'Médico',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/pessoa.jpeg'),
          texto: 'Pessoa',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/professora.jpeg'),
          texto: 'Professora',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 9,
        ),
        // linha 3
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pessoas/professora2.jpeg'),
          texto: 'Colegas',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 0,
        ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/mae.jpeg'),
        //   texto: 'Mãe',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 1,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/avo_mae.jpeg'),
        //   texto: 'Avó',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 2,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/avo_pai.jpeg'),
        //   texto: 'Avô',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 3,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/amigo.jpeg'),
        //   texto: 'Amigo',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 4,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/irmaos.jpeg'),
        //   texto: 'Irmão',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 5,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/sister.jpeg'),
        //   texto: 'Irmã',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 6,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/tio.jpeg'),
        //   texto: 'Tio',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 7,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/tia.jpeg'),
        //   texto: 'Tia',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 8,
        // ),
        // CartaoTabela(
        //   imagem: Image.asset('./assets/cards/pessoas/familia.jpeg'),
        //   texto: 'Família',
        //   tamanhoNaColuna: 1,
        //   tamanhoNaLinha: 2,
        //   indexLinha: 4,
        //   indexColuna: 9,
        // ),
      ],
    ),
    // Pronomes
    TabelaModelo(
      key: Key('1'),
      imagem: './assets/cards/pronomes/default.png',
      id: 1,
      mini: Image.asset('./assets/cards/pronomes/default.png'),
      descricao: 'Pronomes',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Eu',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Meu',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Você',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Seu',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Ele',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Ela',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Dele',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Dela',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Aquilo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Aquele',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),

        // linha 2

        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Aquela',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Eles',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Nós',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Nosso',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Deles',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Delas',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Ninguém',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Nenhuma',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Nenhum',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Esses',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 9,
        ),
      ],
    ),
    // Verbos
    TabelaModelo(
      key: Key('2'),
      imagem: './assets/cards/verbos/correr.jpeg',
      id: 2,
      mini: Image.asset('./assets/cards/verbos/correr.jpeg'),
      descricao: 'Verbos',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Fazer',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Sair',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/ir.jpeg'),
          texto: 'Ir',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Ter',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/ajudar.jpg'),
          texto: 'Ajudar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/correr.jpeg'),
          texto: 'Correr',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/caminar.jpeg'),
          texto: 'Caminhar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/dar.jpg'),
          texto: 'Dar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/parar.jpg'),
          texto: 'Parar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/brincar.jpeg'),
          texto: 'Brincar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),
        // linha 2
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/jogar2.jpeg'),
          texto: 'Jogar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/comer.jpeg'),
          texto: 'Comer',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Estar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/deitar.jpeg'),
          texto: 'Deitar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Dormir',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/acordar2.jpg'),
          texto: 'Acordar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/verbos/subir.jpg'),
          texto: 'Subir',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Cair',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Falar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Abrir',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 9,
        ),
      ],
    ),
    // Sentimentos
    TabelaModelo(
      key: Key('3'),
      imagem: './assets/cards/adjetivos/feliz3.jpg',
      id: 3,
      mini: Image.asset('./assets/cards/adjetivos/feliz3.jpg'),
      descricao: 'Sentimentos',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/adjetivos/alegre.jpg'),
          texto: 'Alegre',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/adjetivos/bravo.jpeg'),
          texto: 'Bravo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/adjetivos/faminto.jpg'),
          texto: 'Faminto',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/adjetivos/triste.jpeg'),
          texto: 'Triste',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/adjetivos/feliz3.jpg'),
          texto: 'Feliz',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Mau',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Bom',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/adjetivos/frio.jpg'),
          texto: 'Frio',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Quente',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Sozinho',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),
        // linha 2
        CartaoTabela(
          imagem: Image.asset('./assets/cards/adjetivos/errado.jpg'),
          texto: 'Errado',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Doce',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Salgado',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Limpo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/adjetivos/sujo.JPG'),
          texto: 'Sujo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Grande',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Melhor',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/pronomes/default.png'),
          texto: 'Pior',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/adjetivos/certo.jpg'),
          texto: 'Certo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/adjetivos/ultimo.png'),
          texto: 'Último',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 9,
        ),
      ],
    ),
    // Coisas
    TabelaModelo(
      key: Key('4'),
      imagem: './assets/cards/coisas/coisas.jpg',
      id: 4,
      mini: Image.asset('./assets/cards/coisas/coisas.jpg'),
      descricao: 'Coisas',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/tv.png'),
          texto: 'TV',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/bola.png'),
          texto: 'Bola',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/computador.png'),
          texto: 'Computador',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/videogame.jpg'),
          texto: 'Video Game',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/casa.png'),
          texto: 'Casa',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/presente.png'),
          texto: 'Presente',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/boneco.jpg'),
          texto: 'Boneco',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/boneca.jpg'),
          texto: 'Boneca',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/balao.jpg'),
          texto: 'Balão',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/carro.jpg'),
          texto: 'Carro',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),

        // linha 2

        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/moto.jpg'),
          texto: 'Moto',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/cd.png'),
          texto: 'CD',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/arvore.png'),
          texto: 'Árvore',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/vento.png'),
          texto: 'Vento',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/nuvem.png'),
          texto: 'Núvem',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/sol.png'),
          texto: 'Sol',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/ceu.png'),
          texto: 'Céu',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/guardachuva.png'),
          texto: 'Guarda-Chuva',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/bicicleta.png'),
          texto: 'Bicicleta',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/aviao.png'),
          texto: 'Avião',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 9,
        ),
        // linha 3
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/dinheiro.png'),
          texto: 'Dinheiro',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/cama.png'),
          texto: 'Cama',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/copo.png'),
          texto: 'Copo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/coisas/elevador.jpg'),
          texto: 'Elevador',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 3,
        ),
      ],
    ),
    // Comidas
    TabelaModelo(
      key: Key('5'),
      imagem: './assets/cards/comidas/comida.jpg',
      id: 5,
      mini: Image.asset('./assets/cards/comidas/comida.jpg'),
      descricao: 'Comidas',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/comida.jpg'),
          texto: 'Comida',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/almoco.jpg'),
          texto: 'Almoço',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/jantar.jpg'),
          texto: 'Jantar',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/cafemanha.jpg'),
          texto: 'Café da Manhã',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/queijo.png'),
          texto: 'Queijo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/bife.png'),
          texto: 'Bife',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/salada2.png'),
          texto: 'Salada',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/margarina.png'),
          texto: 'Margarina',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/manteiga.jpg'),
          texto: 'Manteiga',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/chocolate.png'),
          texto: 'Chocolate',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 0,
          indexColuna: 9,
        ),

        // linha 2

        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/chocolatequente.png'),
          texto: 'Chocolate Quente',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/agua.png'),
          texto: 'Água',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/refri.png'),
          texto: 'Refrigerante',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/lanche.png'),
          texto: 'Lanche',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 3,
        ),

        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/sorvete.png'),
          texto: 'Sorvete',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/sobremesa.png'),
          texto: 'Sobremesa',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/frango.png'),
          texto: 'Frango',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/peixe.png'),
          texto: 'Peixe',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/pao.png'),
          texto: 'Pão',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/presunto.png'),
          texto: 'Presunto',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 2,
          indexColuna: 9,
        ),

        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/leite.png'),
          texto: 'Leite',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/bolo.png'),
          texto: 'Bolo',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/arroz.jpg'),
          texto: 'Arroz',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/feijao.png'),
          texto: 'Feijão',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/tomate.png'),
          texto: 'Tomate',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/maca.png'),
          texto: 'Maça',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/banana.png'),
          texto: 'Banana',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/manga.png'),
          texto: 'Manga',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/uva.png'),
          texto: 'Uva',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: Image.asset('./assets/cards/comidas/suco.png'),
          texto: 'Suco',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 2,
          indexLinha: 4,
          indexColuna: 9,
        ),
      ],
    ),
    // Outras palavras
    TabelaModelo(
      key: Key('6'),
      imagem: './assets/cards/pronomes/default.png',
      id: 6,
      mini: Image.asset('./assets/cards/pronomes/default.png'),
      descricao: 'Outras Palavras',
      conteudoLista: [
        // linha 1
        CartaoTabela(
          imagem: null,
          texto: 'A',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 0,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Ápos',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 0,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Até',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 0,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Com',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 0,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Contra',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 0,
          indexColuna: 4,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'De',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 0,
          indexColuna: 5,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Desde',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 0,
          indexColuna: 6,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Em',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 0,
          indexColuna: 7,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Entre',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 0,
          indexColuna: 8,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Para',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 0,
          indexColuna: 9,
        ),
        //linha 2
        CartaoTabela(
          imagem: null,
          texto: 'Por',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 1,
          indexColuna: 0,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Sem',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 1,
          indexColuna: 1,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Sob',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 1,
          indexColuna: 2,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Sobre',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 1,
          indexColuna: 3,
        ),
        CartaoTabela(
          imagem: null,
          texto: 'Trás',
          tamanhoNaColuna: 1,
          tamanhoNaLinha: 1,
          indexLinha: 1,
          indexColuna: 4,
        ),
      ],
    ),
  ],
);

// Tela Adultos dados

NavBarData adultosData = NavBarData(
  conteudo: [
    VSDModelo(
      key: Key('0'),
      imagem: Const.kImgs[0],
      conteudoLista: [
        'Quero bolo!',
        'Está bom?',
        'Quando fica pronto?',
        'Feliz aniversário!',
        'Estava ótimo'
      ],
      pontosReferencia: [],
      id: 0,
      mini: Image.asset(Const.kImgs[0]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Bolo',
    ),
    VSDModelo(
      key: Key('1'),
      imagem: Const.kImgs[1],
      conteudoLista: [
        'Minha casa!',
        'Quero voltar para casa!',
        'Que casa linda!',
        'As árvores estão crescendo!',
      ],
      pontosReferencia: [],
      id: 1,
      mini: Image.asset(Const.kImgs[1]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Casa',
    ),
    VSDModelo(
      key: Key('2'),
      imagem: Const.kImgs[2],
      conteudoLista: [
        'Estou com fome.',
        'Que horas é o almoço?',
        'Que horas é a janta?',
        'Quero arroz e feijão.',
        'Vamos comer?',
        'Aonde está o garfo?',
      ],
      pontosReferencia: [],
      id: 2,
      mini: Image.asset(Const.kImgs[2]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Comida',
    ),
    VSDModelo(
      key: Key('3'),
      imagem: Const.kImgs[3],
      conteudoLista: [
        'Quanto foi o jogo hoje?',
        'Vamos jogar bola?',
        'Que horas é o jogo?',
        'Quem ganhou?',
        'Ganhamos!',
      ],
      pontosReferencia: [],
      id: 3,
      mini: Image.asset(Const.kImgs[3]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Futebol',
    ),
    VSDModelo(
      key: Key('4'),
      imagem: Const.kImgs[4],
      conteudoLista: [
        'Como estão os gatinhos?',
        'Como são fofos.',
      ],
      pontosReferencia: [],
      id: 4,
      mini: Image.asset(Const.kImgs[4]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Gatos',
    ),
    VSDModelo(
      key: Key('5'),
      imagem: Const.kImgs[5],
      conteudoLista: [
        'Vamos jogar vídeo game?',
        'Me alcança o controle.',
        'Pode colocar o jogo?',
        'Esse mesmo!',
        'Pode começar!',
        'HAHAHA Ganhei!',
        'Droga perdi!',
      ],
      pontosReferencia: [],
      id: 5,
      mini: Image.asset(Const.kImgs[5]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Vídeo game',
    ),
    VSDModelo(
      key: Key('6'),
      imagem: Const.kImgs[6],
      conteudoLista: [
        'Como estão lindos!',
        'Quantos anos estão?',
        'Gostaria de vê-los.',
        'Qual o nome deles?',
        'Onde estão?',
      ],
      pontosReferencia: [],
      id: 6,
      mini: Image.asset(Const.kImgs[6]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Crianças',
    ),
    VSDModelo(
      key: Key('7'),
      imagem: Const.kImgs[7],
      conteudoLista: [
        'Quero comer um hamburguer',
        'Sem alface',
        'Como muito queijo',
        'Me alcança o ketchup',
        'Quer um?',
        'Pode pegar!',
      ],
      pontosReferencia: [],
      id: 7,
      mini: Image.asset(Const.kImgs[7]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Hamburgers',
    ),
    VSDModelo(
      key: Key('8'),
      imagem: Const.kImgs[8],
      conteudoLista: [
        'Quando vamos nos mudar?',
        'Como foi a mudança?',
        'Como estão as crianças?',
        'Se mudaram para onde e quando?',
      ],
      pontosReferencia: [],
      id: 8,
      mini: Image.asset(Const.kImgs[8]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Mudança',
    ),
    VSDModelo(
      key: Key('9'),
      imagem: Const.kImgs[9],
      conteudoLista: null,
      pontosReferencia: [],
      id: 9,
      mini: Image.asset(Const.kImgs[9]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Bebê',
    ),
  ],
);

NavBarData adultosData2 = NavBarData(
  conteudo: [
    VSDModelo(
      key: Key('0'),
      imagem: Const.kImgs[0],
      conteudoLista: [
        'Quero bolo!',
        'Está bom?',
        'Quando fica pronto?',
        'Feliz aniversário!',
        'Estava ótimo'
      ],
      pontosReferencia: [],
      id: 0,
      mini: Image.asset(Const.kImgs[0]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Bolo',
    ),
    VSDModelo(
      key: Key('1'),
      imagem: Const.kImgs[1],
      conteudoLista: [
        'Minha casa!',
        'Quero voltar para casa!',
        'Que casa linda!',
        'As árvores estão crescendo!',
      ],
      pontosReferencia: [],
      id: 1,
      mini: Image.asset(Const.kImgs[1]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Casa',
    ),
    VSDModelo(
      key: Key('2'),
      imagem: Const.kImgs[2],
      conteudoLista: [
        'Estou com fome.',
        'Que horas é o almoço?',
        'Que horas é a janta?',
        'Quero arroz e feijão.',
        'Vamos comer?',
        'Aonde está o garfo?',
      ],
      pontosReferencia: [],
      id: 2,
      mini: Image.asset(Const.kImgs[2]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Comida',
    ),
    VSDModelo(
      key: Key('3'),
      imagem: Const.kImgs[3],
      conteudoLista: [
        'Quanto foi o jogo hoje?',
        'Vamos jogar bola?',
        'Que horas é o jogo?',
        'Quem ganhou?',
        'Ganhamos!',
      ],
      pontosReferencia: [],
      id: 3,
      mini: Image.asset(Const.kImgs[3]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Futebol',
    ),
    VSDModelo(
      key: Key('4'),
      imagem: Const.kImgs[4],
      conteudoLista: [
        'Como estão os gatinhos?',
        'Como são fofos.',
      ],
      pontosReferencia: [],
      id: 4,
      mini: Image.asset(Const.kImgs[4]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Gatos',
    ),
    VSDModelo(
      key: Key('5'),
      imagem: Const.kImgs[5],
      conteudoLista: [
        'Vamos jogar vídeo game?',
        'Me alcança o controle.',
        'Pode colocar o jogo?',
        'Esse mesmo!',
        'Pode começar!',
        'HAHAHA Ganhei!',
        'Droga perdi!',
      ],
      pontosReferencia: [],
      id: 5,
      mini: Image.asset(Const.kImgs[5]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Vídeo game',
    ),
    VSDModelo(
      key: Key('6'),
      imagem: Const.kImgs[6],
      conteudoLista: [
        'Como estão lindos!',
        'Quantos anos estão?',
        'Gostaria de vê-los.',
        'Qual o nome deles?',
        'Onde estão?',
      ],
      pontosReferencia: [],
      id: 6,
      mini: Image.asset(Const.kImgs[6]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Crianças',
    ),
    VSDModelo(
      key: Key('7'),
      imagem: Const.kImgs[7],
      conteudoLista: [
        'Quero comer um hamburguer',
        'Sem alface',
        'Como muito queijo',
        'Me alcança o ketchup',
        'Quer um?',
        'Pode pegar!',
      ],
      pontosReferencia: [],
      id: 7,
      mini: Image.asset(Const.kImgs[7]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Hamburgers',
    ),
    VSDModelo(
      key: Key('8'),
      imagem: Const.kImgs[8],
      conteudoLista: [
        'Quando vamos nos mudar?',
        'Como foi a mudança?',
        'Como estão as crianças?',
        'Se mudaram para onde e quando?',
      ],
      pontosReferencia: [],
      id: 8,
      mini: Image.asset(Const.kImgs[8]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Mudança',
    ),
    VSDModelo(
      key: Key('9'),
      imagem: Const.kImgs[9],
      conteudoLista: null,
      pontosReferencia: [],
      id: 9,
      mini: Image.asset(Const.kImgs[9]),
      indexLinha: 2,
      indexColuna: 2,
      tamanhoNaColuna: 6,
      tamanhoNaLinha: 6,
      descricao: 'Bebê',
    ),
  ],
);
